<?php

return [
    'bodyBackground' => [
        'value'       => '#ffffff',
        'description' => __('Body background', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'textColor' => [
        'value'       => '#333333',
        'description' => __('Text color', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'textEmboss' => [
        'value'       => '#ffffff',
        'description' => __('Text emboss', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'linkColor' => [
        'value'       => '#3d6b99',
        'description' => __('Link', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'linkColorHover' => [
        'value'       => '#335980',
        'description' => __('Link (hover)', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'baseFontFamily' => [
        'value'       => '"Helvetica Neue", Helvetica, Arial, sans-serif',
        'description' => __('Base font', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'font',
    ],
    'baseFontSize' => [
        'value'       => '13px',
        'description' => __('Base font size', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'size',
    ],
    'tableBackground' => [
        'value'       => '#ffffff',
        'description' => __('Table background', 'open-source-event-calendar'),
        'tab'         => 'table',
        'type'        => 'color',
    ],
    'tableLabelBackground' => [
        'value'       => '#f5f5f5',
        'description' => __('Table header background', 'open-source-event-calendar'),
        'tab'         => 'table',
        'type'        => 'color',
    ],
    'tableLabelText' => [
        'value'       => '#9e9e9e',
        'description' => __('Table header text', 'open-source-event-calendar'),
        'tab'         => 'table',
        'type'        => 'color',
    ],
    'btnPrimaryBackground' => [
        'value'       => '#6dbb4f',
        'description' => __('Primary brand color', 'open-source-event-calendar'),
        'tab'         => 'buttons',
        'type'        => 'color',
    ],
    'btnBackground' => [
        'value'       => '#ffffff',
        'description' => __('Button background', 'open-source-event-calendar'),
        'tab'         => 'buttons',
        'type'        => 'color',
    ],
    'btnBorder' => [
        'value'       => '#cccccc',
        'description' => __('Button border', 'open-source-event-calendar'),
        'tab'         => 'buttons',
        'type'        => 'color',
    ],
    'btnTextColor' => [
        'value'       => '#333333',
        'description' => __('Button text', 'open-source-event-calendar'),
        'tab'         => 'buttons',
        'type'        => 'color',
    ],
    'inputText' => [
        'value'       => '#555',
        'description' => __('Input field text', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'inputBackground' => [
        'value'       => '#ffffff',
        'description' => __('Input field background', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'inputBorder' => [
        'value'       => '#cccccc',
        'description' => __('Input field border', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'inputBorderFocus' => [
        'value'       => 'rgba(82,168,236,0.8)',
        'description' => __('Input field border (focus)', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'inputDisabledBackground' => [
        'value'       => '#eeeeee',
        'description' => __('Input field background (disabled)', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'labelColor' => [
        'value'       => '#aaaaaa',
        'description' => __('Field label', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownBackground' => [
        'value'       => '#ffffff',
        'description' => __('Dropdown list background', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownBorder' => [
        'value'       => 'rgba(0,0,0,0.15)',
        'description' => __('Dropdown list border', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownLinkColor' => [
        'value'       => '#333333',
        'description' => __('List item text', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownLinkColorHover' => [
        'value'       => '#262626',
        'description' => __('List item text (active/hover)', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownLinkBackgroundHover' => [
        'value'       => '#f5f5f5',
        'description' => __('List item background (active/hover)', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'placeholderText' => [
        'value'       => '#999999',
        'description' => __('Input field placeholder text', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'todayColor' => [
        'value'       => '#ffffdd',
        'description' => __('Today color', 'open-source-event-calendar'),
        'tab'         => 'calendar',
        'type'        => 'color',
    ],
    'alldayBadgeGradientMiddle' => [
        'value'       => '#3d6b99',
        'description' => __('All-day badge color', 'open-source-event-calendar'),
        'tab'         => 'calendar',
        'type'        => 'color',
    ],
    'eventImageShadow' => [
        'value'       => 'rgba(0,0,0,0.4)',
        'description' => __('Event image shadow', 'open-source-event-calendar'),
        'tab'         => 'calendar',
        'type'        => 'color',
    ],
    'eventDefaultColor' => [
        'value'       => '#3d6b99',
        'description' => __('Event default color', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventDefaultColorHover' => [
        'value'       => '#335980',
        'description' => __('Event default color (hover)', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventStubAllDayText' => [
        'value'       => '#ffffff',
        'description' => __('All-day/multi-day event stub text', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventStubAllDayTextShadow' => [
        'value'       => 'rgba(0,0,0,0.4)',
        'description' => __('All-day/multi-day event stub text shadow', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventBorder' => [
        'value'       => '#cccccc',
        'description' => __('Event border', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventBackground' => [
        'value'       => '#ffffff',
        'description' => __('Event background', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventTimeBackground' => [
        'value'       => '#eeeeee',
        'description' => __('Event time background', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventText' => [
        'value'       => '#333333',
        'description' => __('Event text', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'monthViewDateBackground' => [
        'value'       => '#eaf4ff',
        'description' => __('Month view date background', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'dayViewNowMarkerColor' => [
        'value'       => '#f2c539',
        'description' => __('Week/day view now marker', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'agendaDateTitleBorder' => [
        'value'       => '#6689AC',
        'description' => __('Date label accent color', 'open-source-event-calendar'),
        'tab'         => 'agenda',
        'type'        => 'color',
    ],
    'agendaDateTitleBackground' => [
        'value'       => '#ffffff',
        'description' => __('Date label background', 'open-source-event-calendar'),
        'tab'         => 'agenda',
        'type'        => 'color',
    ],
    'agendaDateBackground' => [
        'value'       => '#f2f2f2',
        'description' => __('Date background', 'open-source-event-calendar'),
        'tab'         => 'agenda',
        'type'        => 'color',
    ],
    'agendaTodayBackground' => [
        'value'       => '#f4f4bf',
        'description' => __('Today background', 'open-source-event-calendar'),
        'tab'         => 'agenda',
        'type'        => 'color',
    ],
];
