<?php
return [
  "bodyBackground" => [
    "value" => "#ffffff",
    "description" => __("Body background", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "textColor" => [
    "value" => "#333333",
    "description" => __("Text color", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "textEmboss" => [
    "value" => "#ffffff",
    "description" => __("Text emboss", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "linkColor" => [
    "value" => "#3d6b99",
    "description" => __("Link", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "linkColorHover" => [
    "value" => "#335980",
    "description" => __("Link (hover)", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "baseFontFamily" => [
    "value" => "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
    "description" => __("Base font", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "font",
  ],
  "baseFontSize" => [
    "value" => "13px",
    "description" => __("Base font size", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "size",
  ],
  "tableBackground" => [
    "value" => "#ffffff",
    "description" => __("Table background", OSEC_TXT_DOM),
    "tab" => "table",
    "type" => "color",
  ],
  "tableLabelBackground" => [
    "value" => "#f5f5f5",
    "description" => __("Table header background", OSEC_TXT_DOM),
    "tab" => "table",
    "type" => "color",
  ],
  "tableLabelText" => [
    "value" => "#9e9e9e",
    "description" => __("Table header text", OSEC_TXT_DOM),
    "tab" => "table",
    "type" => "color",
  ],
  "btnPrimaryBackground" => [
    "value" => "#6dbb4f",
    "description" => __("Primary brand color", OSEC_TXT_DOM),
    "tab" => "buttons",
    "type" => "color",
  ],
  "btnBackground" => [
    "value" => "#ffffff",
    "description" => __("Button background", OSEC_TXT_DOM),
    "tab" => "buttons",
    "type" => "color",
  ],
  "btnBorder" => [
    "value" => "#cccccc",
    "description" => __("Button border", OSEC_TXT_DOM),
    "tab" => "buttons",
    "type" => "color",
  ],
  "btnTextColor" => [
    "value" => "#333333",
    "description" => __("Button text", OSEC_TXT_DOM),
    "tab" => "buttons",
    "type" => "color",
  ],
  "inputText" => [
    "value" => "#555",
    "description" => __("Input field text", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "inputBackground" => [
    "value" => "#ffffff",
    "description" => __("Input field background", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "inputBorder" => [
    "value" => "#cccccc",
    "description" => __("Input field border", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "inputBorderFocus" => [
    "value" => "rgba(82,168,236,0.8)",
    "description" => __("Input field border (focus)", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "inputDisabledBackground" => [
    "value" => "#eeeeee",
    "description" => __("Input field background (disabled)", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "labelColor" => [
    "value" => "#aaaaaa",
    "description" => __("Field label", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownBackground" => [
    "value" => "#ffffff",
    "description" => __("Dropdown list background", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownBorder" => [
    "value" => "rgba(0,0,0,0.15)",
    "description" => __("Dropdown list border", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownLinkColor" => [
    "value" => "#333333",
    "description" => __("List item text", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownLinkColorHover" => [
    "value" => "#262626",
    "description" => __("List item text (active/hover)", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownLinkBackgroundHover" => [
    "value" => "#f5f5f5",
    "description" => __("List item background (active/hover)", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "placeholderText" => [
    "value" => "#999999",
    "description" => __("Input field placeholder text", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "todayColor" => [
    "value" => "#ffffdd",
    "description" => __("Today color", OSEC_TXT_DOM),
    "tab" => "calendar",
    "type" => "color",
  ],
  "alldayBadgeGradientMiddle" => [
    "value" => "#3d6b99",
    "description" => __("All-day badge color", OSEC_TXT_DOM),
    "tab" => "calendar",
    "type" => "color",
  ],
  "eventImageShadow" => [
    "value" => "rgba(0,0,0,0.4)",
    "description" => __("Event image shadow", OSEC_TXT_DOM),
    "tab" => "calendar",
    "type" => "color",
  ],
  "eventDefaultColor" => [
    "value" => "#3d6b99",
    "description" => __("Event default color", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventDefaultColorHover" => [
    "value" => "#335980",
    "description" => __("Event default color (hover)", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventStubAllDayText" => [
    "value" => "#ffffff",
    "description" => __("All-day/multi-day event stub text", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventStubAllDayTextShadow" => [
    "value" => "rgba(0,0,0,0.4)",
    "description" => __("All-day/multi-day event stub text shadow", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventBorder" => [
    "value" => "#cccccc",
    "description" => __("Event border", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventBackground" => [
    "value" => "#ffffff",
    "description" => __("Event background", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventTimeBackground" => [
    "value" => "#eeeeee",
    "description" => __("Event time background", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventText" => [
    "value" => "#333333",
    "description" => __("Event text", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "monthViewDateBackground" => [
    "value" => "#eaf4ff",
    "description" => __("Month view date background", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "dayViewNowMarkerColor" => [
    "value" => "#f2c539",
    "description" => __("Week/day view now marker", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "agendaDateTitleBorder" => [
    "value" => "#6689AC",
    "description" => __("Date label accent color", OSEC_TXT_DOM),
    "tab" => "agenda",
    "type" => "color",
  ],
  "agendaDateTitleBackground" => [
    "value" => "#ffffff",
    "description" => __("Date label background", OSEC_TXT_DOM),
    "tab" => "agenda",
    "type" => "color",
  ],
  "agendaDateBackground" => [
    "value" => "#f2f2f2",
    "description" => __("Date background", OSEC_TXT_DOM),
    "tab" => "agenda",
    "type" => "color",
  ],
  "agendaTodayBackground" => [
    "value" => "#f4f4bf",
    "description" => __("Today background", OSEC_TXT_DOM),
    "tab" => "agenda",
    "type" => "color",
  ],
];
