# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1
orbs:
  php: circleci/php@1.1.0


# References section
#   @see https://carlalexander.ca/continuous-deployment-wordpress-directory-circleci/
#
references:
  # Environment variables
  #
  WP_CORE_DIR: &WP_CORE_DIR
                /tmp/wordpress
  WP_HOST: &WP_HOST
              open-source-event-calendar.test
  WP_ORG_PLUGIN_NAME: &WP_ORG_PLUGIN_NAME
              open-source-event-calendar
  WP_ORG_USERNAME: &WP_ORG_USERNAME
               digitaldonkey
  workspace_root: &workspace_root /tmp

  # Default container configuration
  #
  container_config: &container_config
    docker:
      - image: cimg/php:8.2-node
    environment:
      - WP_CORE_DIR: *WP_CORE_DIR
      - WP_HOST: *WP_HOST
      - WP_ORG_PLUGIN_NAME: *WP_ORG_PLUGIN_NAME
      - WP_ORG_USERNAME: *WP_ORG_USERNAME
    working_directory: ~/open-source-event-calendar

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  copy_vendor: &copy_vendor
    run:
      name: Copy vendor directory
      command: cp -R /tmp/vendor .

  install_subversion: &install_subversion
    run:
      name: Install subversion
      command: sudo apt-get update && sudo apt-get install -y subversion && sudo rm -rf /var/lib/apt/lists/*


# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:

  # BUILD
  build:
    <<: *container_config
    steps:
      - checkout
#      - run: php --version
#      - run: node --version
      - run:
          name: Install dependencies
          command: composer install --no-interaction --optimize-autoloader
          # --no-dev Option required for production build
      - persist_to_workspace:
          root: .
          paths:
            - vendor
      - *install_subversion
      - run:
          name: Install WordPress
          command: bash ./bin/install-wp-tests.sh wp_ci wp_ci wp_ci $WP_HOST 6.6.2 true
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - wordpress
            - wordpress-tests-lib

  # STATIC CODE ANALYSE
  code_quality_job:
    <<: *container_config
    steps:
      - checkout
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Run code quality tests
          command: vendor/bin/grumphp run --testsuite=code_quality

#  # DB / PHPUNIT
#  phpunit_job: &phpunit_job
#    <<: *container_config
#    steps:
#      - checkout
#      - *attach_workspace
#      - *copy_vendor
#      - run:
#          name: Run PHP unit tests
#          command: vendor/bin/phpunit

  #
  # Default configuration Database testing jobs
  #
  db_job: &db_job
    <<: *container_config
    docker:
      - image: cimg/php:8.2-node
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ROOT_PASSWORD: wp_ci_root
          MYSQL_USER: wp_ci
          MYSQL_DATABASE: wp_ci
          MYSQL_PASSWORD: wp_ci
    steps:
      - checkout
      - run:
          name: Add WordPress host to hosts file
          command: echo "127.0.0.1 ${WP_HOST}" | sudo tee -a /etc/hosts
      - *attach_workspace
      - *copy_vendor
      - run:
          name: Update outdated apt key
          command: (cd /etc/apt/ && sudo cp trusted.gpg trusted.gpg.d/)

      - run:
          name: Update outdated apt key
          command: sudo mkdir -p /etc/apt/trusted.gpg.d/ 
                      && sudo cp /etc/apt/trusted.gpg /etc/apt/trusted.gpg.d/trusted.gpg
      - run:
          name: Install MySQL client and PHP extension
          command: sudo apt-get update
                    && sudo apt-get install -y mysql-client 
                    && sudo rm -rf /var/lib/apt/lists/*
      - run:
          name: Install apcu
          command: sudo mkdir -p /tmp/pear/temp
                    && sudo pecl channel-update pecl.php.net
                    && echo no '' |  sudo pecl install apcu
      - run:
          name: Start PHP server
          command: sudo php -S $WP_HOST:80 -t $WP_CORE_DIR
          background: True
      #      - run:
      #          name: Run Behat tests
      #          command: vendor/bin/behat --config .circleci/behat.yml --format progress --tags=$WP_TYPE

#      - run:
#          name: Run PHP unit tests
#          command: vendor/bin/phpunit
      - run:
          name: Run PHP unit tests
          command: |
            set -Eeuxo pipefail
            mkdir -p ~/phpunit          
            vendor/bin/phpunit --log-junit ~/phpunit/junit.xml tests
          when: always
      - store_test_results:
          path: ~/phpunit
  #        environment:
  #          MYSQL_ROOT_PASSWORD: rootpw
  #          MYSQL_DATABASE: osec
  #          MYSQL_USER: osec
  #          MYSQL_PASSWORD: osec

#  say-hello:
#    # Specify the execution environment. You can specify an image from Docker Hub or use one of our convenience images from CircleCI's Developer Hub.
#    # See: https://circleci.com/docs/executor-intro/ & https://circleci.com/docs/configuration-reference/#executor-job
#    docker:
#      # Specify the version you desire here
#      # See: https://circleci.com/developer/images/image/cimg/base
#      - image: cimg/base:current
#
#    # Add steps to the job
#    # See: https://circleci.com/docs/jobs-steps/#steps-overview & https://circleci.com/docs/configuration-reference/#steps
#    steps:
#      # Checkout the code as the first step.
#      - checkout
#      - run:
#          name: "Say hello"
#          command: "echo Hello, World!"

#  -      - run:
#  -          name: Install WordPress
#  -          command: bash ./bin/install-wp-tests.sh wp_ci wp_ci wp_ci localhost:3306 6.6.1


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build_test_deploy: # This is the name of the workflow, feel free to change it to better match your workflow.
    # Inside the workflow, you define the jobs you want to run.
    jobs:
      - build
      - code_quality_job:
          requires:
            - build
      - db_job:
          requires:
            - build
