<?php

return [
    'bodyBackground' => [
        'value'       => '#000000',
        'description' => __('Body background', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'textColor' => [
        'value'       => '#b0b0b0',
        'description' => __('Text color', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'textEmboss' => [
        'value'       => 'rgba(0,0,0,0)',
        'description' => __('Text emboss', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'linkColor' => [
        'value'       => '#5e8cba',
        'description' => __('Link', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'linkColorHover' => [
        'value'       => '#94b2d1',
        'description' => __('Link (hover)', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'color',
    ],
    'baseFontFamily' => [
        'value'       => "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
        'description' => __('Base font', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'font',
    ],
    'baseFontSize' => [
        'value'       => '13px',
        'description' => __('Base font size', 'open-source-event-calendar'),
        'tab'         => 'general',
        'type'        => 'size',
    ],
    'tableBackground' => [
        'value'       => '#000000',
        'description' => __('Table background', 'open-source-event-calendar'),
        'tab'         => 'table',
        'type'        => 'color',
    ],
    'tableLabelBackground' => [
        'value'       => '#303030',
        'description' => __('Table header background', 'open-source-event-calendar'),
        'tab'         => 'table',
        'type'        => 'color',
    ],
    'tableLabelText' => [
        'value'       => '#6a6a6a',
        'description' => __('Table header text', 'open-source-event-calendar'),
        'tab'         => 'table',
        'type'        => 'color',
    ],
    'btnPrimaryBackground' => [
        'value'       => '#5e8cba',
        'description' => __('Primary brand color', 'open-source-event-calendar'),
        'tab'         => 'buttons',
        'type'        => 'color',
    ],
    'btnBackground' => [
        'value'       => '#2b2b2b',
        'description' => __('Button background', 'open-source-event-calendar'),
        'tab'         => 'buttons',
        'type'        => 'color',
    ],
    'btnBorder' => [
        'value'       => '#000000',
        'description' => __('Button border', 'open-source-event-calendar'),
        'tab'         => 'buttons',
        'type'        => 'color',
    ],
    'btnTextColor' => [
        'value'       => '#b0b0b0',
        'description' => __('Button text', 'open-source-event-calendar'),
        'tab'         => 'buttons',
        'type'        => 'color',
    ],
    'inputText' => [
        'value'       => '#bbb',
        'description' => __('Input field text', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'inputBackground' => [
        'value'       => '#000000',
        'description' => __('Input field background', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'inputBorder' => [
        'value'       => '#404040',
        'description' => __('Input field border', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'inputBorderFocus' => [
        'value'       => 'rgba(82,168,236,0.8)',
        'description' => __('Input field border (focus)', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'inputDisabledBackground' => [
        'value'       => '#303030',
        'description' => __('Input field background (disabled)', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'labelColor' => [
        'value'       => '#999999',
        'description' => __('Field label', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownBackground' => [
        'value'       => '#000000',
        'description' => __('Dropdown list background', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownBorder' => [
        'value'       => 'rgba(255,255,255,0.15)',
        'description' => __('Dropdown list border', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownLinkColor' => [
        'value'       => '#999999',
        'description' => __('List item text', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownLinkColorHover' => [
        'value'       => '#dddddd',
        'description' => __('List item text (active/hover)', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'dropdownLinkBackgroundHover' => [
        'value'       => '#003a66',
        'description' => __('List item background (active/hover)', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'placeholderText' => [
        'value'       => '#555',
        'description' => __('Input field placeholder text', 'open-source-event-calendar'),
        'tab'         => 'forms',
        'type'        => 'color',
    ],
    'todayColor' => [
        'value'       => '#002743',
        'description' => __('Today color', 'open-source-event-calendar'),
        'tab'         => 'calendar',
        'type'        => 'color',
    ],
    'alldayBadgeGradientMiddle' => [
        'value'       => '#5e8cba',
        'description' => __('All-day badge color', 'open-source-event-calendar'),
        'tab'         => 'calendar',
        'type'        => 'color',
    ],
    'eventImageShadow' => [
        'value'       => 'rgba(0,0,0,0.3)',
        'description' => __('Event image shadow', 'open-source-event-calendar'),
        'tab'         => 'calendar',
        'type'        => 'color',
    ],
    'eventDefaultColor' => [
        'value'       => '#5e8cba',
        'description' => __('Event default color', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventDefaultColorHover' => [
        'value'       => '#94b2d1',
        'description' => __('Event default color (hover)', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventStubAllDayText' => [
        'value'       => '#000000',
        'description' => __('All-day/multi-day event stub text', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventStubAllDayTextShadow' => [
        'value'       => 'rgba(255,255,255,0.4)',
        'description' => __('All-day/multi-day event stub text shadow', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventBorder' => [
        'value'       => '#404040',
        'description' => __('Event border', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventBackground' => [
        'value'       => '#222222',
        'description' => __('Event background', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventTimeBackground' => [
        'value'       => '#000000',
        'description' => __('Event time background', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'eventText' => [
        'value'       => '#b0b0b0',
        'description' => __('Event text', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'monthViewDateBackground' => [
        'value'       => '#001829',
        'description' => __('Month view date background', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'dayViewNowMarkerColor' => [
        'value'       => '#f2c539',
        'description' => __('Week/day view now marker', 'open-source-event-calendar'),
        'tab'         => 'month',
        'type'        => 'color',
    ],
    'agendaDateTitleBorder' => [
        'value'       => '#35597d',
        'description' => __('Date label accent color', 'open-source-event-calendar'),
        'tab'         => 'agenda',
        'type'        => 'color',
    ],
    'agendaDateTitleBackground' => [
        'value'       => '#000000',
        'description' => __('Date label background', 'open-source-event-calendar'),
        'tab'         => 'agenda',
        'type'        => 'color',
    ],
    'agendaDateBackground' => [
        'value'       => '#222222',
        'description' => __('Date background', 'open-source-event-calendar'),
        'tab'         => 'agenda',
        'type'        => 'color',
    ],
    'agendaTodayBackground' => [
        'value'       => '#040e16',
        'description' => __('Today background', 'open-source-event-calendar'),
        'tab'         => 'agenda',
        'type'        => 'color',
    ],
];
