<?php
return [
  "bodyBackground" => [
    "value" => "#000000",
    "description" => __("Body background", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "textColor" => [
    "value" => "#b0b0b0",
    "description" => __("Text color", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "textEmboss" => [
    "value" => "rgba(0,0,0,0)",
    "description" => __("Text emboss", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "linkColor" => [
    "value" => "#5e8cba",
    "description" => __("Link", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "linkColorHover" => [
    "value" => "#94b2d1",
    "description" => __("Link (hover)", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "color",
  ],
  "baseFontFamily" => [
    "value" => "\"Helvetica Neue\", Helvetica, Arial, sans-serif",
    "description" => __("Base font", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "font",
  ],
  "baseFontSize" => [
    "value" => "13px",
    "description" => __("Base font size", OSEC_TXT_DOM),
    "tab" => "general",
    "type" => "size",
  ],
  "tableBackground" => [
    "value" => "#000000",
    "description" => __("Table background", OSEC_TXT_DOM),
    "tab" => "table",
    "type" => "color",
  ],
  "tableLabelBackground" => [
    "value" => "#303030",
    "description" => __("Table header background", OSEC_TXT_DOM),
    "tab" => "table",
    "type" => "color",
  ],
  "tableLabelText" => [
    "value" => "#6a6a6a",
    "description" => __("Table header text", OSEC_TXT_DOM),
    "tab" => "table",
    "type" => "color",
  ],
  "btnPrimaryBackground" => [
    "value" => "#5e8cba",
    "description" => __("Primary brand color", OSEC_TXT_DOM),
    "tab" => "buttons",
    "type" => "color",
  ],
  "btnBackground" => [
    "value" => "#2b2b2b",
    "description" => __("Button background", OSEC_TXT_DOM),
    "tab" => "buttons",
    "type" => "color",
  ],
  "btnBorder" => [
    "value" => "#000000",
    "description" => __("Button border", OSEC_TXT_DOM),
    "tab" => "buttons",
    "type" => "color",
  ],
  "btnTextColor" => [
    "value" => "#b0b0b0",
    "description" => __("Button text", OSEC_TXT_DOM),
    "tab" => "buttons",
    "type" => "color",
  ],
  "inputText" => [
    "value" => "#bbb",
    "description" => __("Input field text", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "inputBackground" => [
    "value" => "#000000",
    "description" => __("Input field background", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "inputBorder" => [
    "value" => "#404040",
    "description" => __("Input field border", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "inputBorderFocus" => [
    "value" => "rgba(82,168,236,0.8)",
    "description" => __("Input field border (focus)", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "inputDisabledBackground" => [
    "value" => "#303030",
    "description" => __("Input field background (disabled)", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "labelColor" => [
    "value" => "#999999",
    "description" => __("Field label", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownBackground" => [
    "value" => "#000000",
    "description" => __("Dropdown list background", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownBorder" => [
    "value" => "rgba(255,255,255,0.15)",
    "description" => __("Dropdown list border", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownLinkColor" => [
    "value" => "#999999",
    "description" => __("List item text", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownLinkColorHover" => [
    "value" => "#dddddd",
    "description" => __("List item text (active/hover)", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "dropdownLinkBackgroundHover" => [
    "value" => "#003a66",
    "description" => __("List item background (active/hover)", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "placeholderText" => [
    "value" => "#555",
    "description" => __("Input field placeholder text", OSEC_TXT_DOM),
    "tab" => "forms",
    "type" => "color",
  ],
  "todayColor" => [
    "value" => "#002743",
    "description" => __("Today color", OSEC_TXT_DOM),
    "tab" => "calendar",
    "type" => "color",
  ],
  "alldayBadgeGradientMiddle" => [
    "value" => "#5e8cba",
    "description" => __("All-day badge color", OSEC_TXT_DOM),
    "tab" => "calendar",
    "type" => "color",
  ],
  "eventImageShadow" => [
    "value" => "rgba(0,0,0,0.3)",
    "description" => __("Event image shadow", OSEC_TXT_DOM),
    "tab" => "calendar",
    "type" => "color",
  ],
  "eventDefaultColor" => [
    "value" => "#5e8cba",
    "description" => __("Event default color", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventDefaultColorHover" => [
    "value" => "#94b2d1",
    "description" => __("Event default color (hover)", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventStubAllDayText" => [
    "value" => "#000000",
    "description" => __("All-day/multi-day event stub text", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventStubAllDayTextShadow" => [
    "value" => "rgba(255,255,255,0.4)",
    "description" => __("All-day/multi-day event stub text shadow", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventBorder" => [
    "value" => "#404040",
    "description" => __("Event border", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventBackground" => [
    "value" => "#222222",
    "description" => __("Event background", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventTimeBackground" => [
    "value" => "#000000",
    "description" => __("Event time background", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "eventText" => [
    "value" => "#b0b0b0",
    "description" => __("Event text", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "monthViewDateBackground" => [
    "value" => "#001829",
    "description" => __("Month view date background", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "dayViewNowMarkerColor" => [
    "value" => "#f2c539",
    "description" => __("Week/day view now marker", OSEC_TXT_DOM),
    "tab" => "month",
    "type" => "color",
  ],
  "agendaDateTitleBorder" => [
    "value" => "#35597d",
    "description" => __("Date label accent color", OSEC_TXT_DOM),
    "tab" => "agenda",
    "type" => "color",
  ],
  "agendaDateTitleBackground" => [
    "value" => "#000000",
    "description" => __("Date label background", OSEC_TXT_DOM),
    "tab" => "agenda",
    "type" => "color",
  ],
  "agendaDateBackground" => [
    "value" => "#222222",
    "description" => __("Date background", OSEC_TXT_DOM),
    "tab" => "agenda",
    "type" => "color",
  ],
  "agendaTodayBackground" => [
    "value" => "#040e16",
    "description" => __("Today background", OSEC_TXT_DOM),
    "tab" => "agenda",
    "type" => "color",
  ],
];
